# Copyright 2025 Colton Loftus
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "toggle_by_mic_status"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
objc2-core-audio = "0.3.1"
mac-notification-sys = "0.6"
